name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate snake.svg

    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: zmartinl
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Modify SVG to change square color to black
        run: |
          sed -i 's/#ffffff/#000000/g' dist/github-contribution-grid-snake.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
